version: '3'

services:
#  vault-server:
#    container_name: dunder-mifflin-stocks-vault
#    image: vault:latest
#    ports:
#      - "8200:8200"
#    environment:
#      VAULT_ADDR: "http://0.0.0.0:8200"
#      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
#      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
  postgresql-licenses:
    container_name: dunder-mifflin-stocks-licenses-pg-db
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5433:5432"
    volumes:
      - "postgresql-licenses-data:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dunder-mifflin-stocks-licenses-dev
  postgresql-organizations:
    container_name: dunder-mifflin-stocks-organizations-pg-db
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5434:5432"
    volumes:
      - "postgresql-organizations-data:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dunder-mifflin-stocks-organizations-dev
  postgresql-adminer:
    container_name: dunder-mifflin-stocks-pgadminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dunder-mifflin-stocks-postgresql
#  configserver:
#    container_name: inc.dunder-mifflin.stocks/config-server
#    image: inc.dunder-mifflin.stocks/config-server:0.0.1-SNAPSHOT
#    ports:
#      - "8071:8071"
#  licensingservice:
#    depends_on:
#      - configserver
#    container_name: inc.dunder-mifflin.stocks/licensing-service
#    image: inc.dunder-mifflin.stocks/licensing-service:0.0.1-SNAPSHOT
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: "dev"
volumes:
  postgresql-licenses-data:
    driver: local
  postgresql-organizations-data:
    driver: local