version: '3'

services:
  #  vault-server:
  #    container_name: dunder-mifflin-stocks-vault
  #    image: vault:latest
  #    ports:
  #      - "8200:8200"
  #    environment:
  #      VAULT_ADDR: "http://0.0.0.0:8200"
  #      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
  #      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
  postgres-keycloak:
    container_name: dunder-mifflin-stocks-keycloak-db
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - "postgresql-keycloak-data:/var/lib/postgresql"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

    ports:
      - "5435:5432"
  keycloak:
    container_name: dunder-mifflin-stocks-keycloak
#    image: jboss/keycloak:latest
    image: jboss/keycloak:13.0.1 #build it locally on M1 Chip
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      - postgres-keycloak
  postgresql-licenses:
    container_name: dunder-mifflin-stocks-licenses-pg-db
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5433:5432"
    volumes:
      - "postgresql-licenses-data:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dunder-mifflin-stocks-licenses-dev
  postgresql-organizations:
    container_name: dunder-mifflin-stocks-organizations-pg-db
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5434:5432"
    volumes:
      - "postgresql-organizations-data:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dunder-mifflin-stocks-organizations-dev
  postgresql-adminer:
    container_name: dunder-mifflin-stocks-pgadminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dunder-mifflin-stocks-postgresql
#  configserver:
#    container_name: inc.dunder-mifflin.stocks/config-server
#    image: inc.dunder-mifflin.stocks/config-server:0.0.1-SNAPSHOT
#    ports:
#      - "8071:8071"
#  licensingservice:
#    depends_on:
#      - configserver
#    container_name: inc.dunder-mifflin.stocks/licensing-service
#    image: inc.dunder-mifflin.stocks/licensing-service:0.0.1-SNAPSHOT
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: "dev"
volumes:
  postgresql-licenses-data:
    driver: local
  postgresql-organizations-data:
    driver: local
  postgresql-keycloak-data:
    driver: local