global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'licensing-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
#      - targets: ['localhost:8888', 'docker.host.internal:8888', 'docker.for.mac.localhost:8888']
      - targets: ['docker.for.mac.localhost:8888']
  - job_name: 'organization-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
#      - targets: ['localhost:8889', 'docker.host.internal:8889', 'docker.for.mac.localhost:8889']
      - targets: ['docker.for.mac.localhost:8889']