###
POST http://127.0.0.1:8888/actuator/refresh
Content-Type: application/json

###
GET http://127.0.0.1:8888/actuator/env
Content-Type: application/json

###
GET http://localhost:8888/api/v1/organizations/b87cf126-2527-4980-9235-8945a8289e4b/licenses/1111-4444
Content-Type: application/json

### circuit breaker in action
GET http://localhost:8888/api/v1/organizations/b87cf126-2527-4980-9235-8945a8289e4b/licenses
Content-Type: application/json
tmx-correlation-id: 123456

###
POST http://localhost:8888/api/v1/organizations/1/licenses
Content-Type: application/json
Accept-Language: es

{
  "licenseId": "1111-4444",
  "description": "Scranton Paper License",
  "organizationId": "123-456-789",
  "productName": "Premium Copy Paper",
  "licenseType": "FULL"
}

###
DELETE http://localhost:8888/api/v1/organizations/1/licenses/1
Content-Type: application/json

###
PUT http://localhost:8888/api/v1/organizations/1/licenses
Content-Type: application/json
Accept-Language: es

{
  "licenseId": "1111-4444",
  "description": "Scranton Paper License",
  "organizationId": "123-456-789",
  "productName": "Premium Copy Paper",
  "licenseType": "FULL"
}

