
###
GET http://localhost:8889/api/v1/organizations/b87cf126-2527-4980-9235-8945a8289e4b
Content-Type: application/json

###
POST http://localhost:8889/api/v1/organizations
Content-Type: application/json

{
  "name": "JetBrains",
  "contactName": "Tehir Galeef",
  "contactEmail": "jetbrains@mail.com",
  "contactPhone": "+48946542164"
}

###
DELETE http://localhost:8889/api/v1/organizations
Content-Type: application/json

###
PUT http://localhost:8889/api/v1/organizations
Content-Type: application/json
Accept-Language: es

{
  "id": 1,
  "licenseId": "1111-4444",
  "description": "IntelliJ License",
  "organizationId": "1",
  "productName": "IntelliJ",
  "licenseType": "FULL"
}

