eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      discovery.locator:
        enabled: true
        loweCaseServiceId: true
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<path>.*), /$\{path}
            - AddRequestHeader=X-Example-Request-Header-ID,F39s2
            - AddResponseHeader=X-Example-Response-Header-ID,F39s2
            #This configuration is a blacklist of the sensitive headers that the gateway will keep from being
            #propagated to a downstream service. The absence of the Authorization value in the RemoveRequestHeader
            #list means that the gateway will allow that header through. If we don’t set this configuration property,
            #the gateway automatically blocks the propagation of all three values (Cookie, Set-Cookie, and Authorization).
            - RemoveRequestHeader=Cookie,Set-Cookie
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/licenses/**
          filters:
            - RewritePath=/licenses/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,Set-Cookie


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    inc.dundermifflin.stocks: INFO
